
try:                                # The try block lets you test a block of code for errors
    print(x)

except:                             # except block lets you handle the error
    print("an error occured")

finally:                            # The finally block lets you execute code, regardless of the result of the try- and except blocks.
    print("success")